---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-distributed-tracing
  labels:
    kubernetes.io/metadata.name: openshift-distributed-tracing
    openshift.io/cluster-monitoring: "true"
