global:
  resolve_timeout: 5m
  smtp_from: admin@localhost
  smtp_smarthost: 'emailrelay.bsc.bscal.com:25'
  smtp_hello: localhost
  smtp_require_tls: false
inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_match:
      severity: critical
    target_match_re:
      severity: warning|info
  - equal:
      - namespace
      - alertname
    source_match:
      severity: warning
    target_match_re:
      severity: info
receivers:
  - name: Default
    email_configs:
      - to: openshifticeops@blueshieldca.com
        from: openshift-alerting-hitk8s@blueshieldca.com
  - name: Watchdog
  - name: Critical
    email_configs:
      - to: openshifticeops@blueshieldca.com
        from: openshift-alerting-hitk8s@blueshieldca.com
route:
  group_by:
    - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: Default
  repeat_interval: 12h
  routes:
    - match:
        alertname: Watchdog
      receiver: Watchdog
    - receiver: Critical
      match:
        severity: critical
