apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: ldapidp
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - sAMAccountName
      bindDN: "CN=svc_openshift,OU=Service Accounts,OU=Global,DC=bsc,DC=bscal,DC=com"
      bindPassword:
        name: ldap-secret
      ca:
        name: bsc-ca
      insecure: false
      url: "ldaps://dir-bsc.bsc.bscal.com/dc=bsc,dc=bscal,dc=com?sAMAccountName"

