---
- op: add
  path: "/spec/identityProviders/-"
  value:
    htpasswd:	
      fileData:	
        name: htpasswd-eclipse-che	
    mappingMethod: claim	
    name: htpasswd-eclipse-che	
    type: HTPasswd
