---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/kube-ops-view/

patches:
  - target:
      kind: Deployment
      name: kube-ops-view
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: "hjacobs/kube-ops-view:23.5.0"
  