apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: external-secrets-venafi-ss
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    webhook:
      url: "https://cert-mgmt.corp.opentlc.com/vedauth/authorize/oauth"
      method: POST
      timeout: 1m
      result:
        jsonPath: "$.access_token"
      headers:
        Content-Type: application/json
        Accept: application/json
      body: |
        {"username": "{{ .auth.username }}", "password": "{{ .auth.password }}", "client_id": "Cert-Manage", "scope": "certificate:manage", "state": "string", "redirect_uri": "string"}
      secrets:
      - name: auth
        secretRef:
          name: external-secrets-venafi-sa-secret
