apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-venafi-es
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "720h"
  secretStoreRef:
    name: external-secrets-venafi-ss
    kind: SecretStore
  target:
    name: external-secrets-venafi-token-secret
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: access_token
      metadataPolicy: None
    secretKey: access-token