apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: external-secrets-vault-ss
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  conditions:
    # Allowed namespaces to access vault with these credentials
    - namespaces:
      - cert-manager
      - openshift-config
      - openshift-workload-availability
      - powerflex
  provider:
    vault:
      auth: 
        jwt:
          kubernetesServiceAccountToken:
            serviceAccountRef:
              # These parameters were chosen to match the previous config in Vault
              audiences:
                - 'https://kubernetes.default.svc'
              name: default
              namespace: openshift-config
          path: override-per-cluster
          role: default
      path: kv-v2/openshift-platform-services
      server: https://vault-nonprod.jobu.net
      version: v2