apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-venafi-sa-secret
  namespace: cert-manager
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default	
        decodingStrategy: None
        key: cert-manager/venafi-sa-secret
        metadataPolicy: None
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets-vault-ss
  target:
    creationPolicy: Owner
    name: external-secrets-venafi-sa-secret
    template:
      metadata:
        labels:
          external-secrets.io/type: webhook