apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocp-operatorconfig.yaml
  #- ./external-secrets-oc.yaml
  - ./external-secrets-vault-ss.yaml
  - ./external-secrets-venafi-sa-secret.yaml 
  - ./external-secrets-venafi-ss.yaml
  - ./external-secrets-venafi-es.yaml 
