---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/aap-operator/
  
patches:
  - target:
      kind: OperatorPolicy
      name: aap-operator-policy
    patch: |
      - op: replace
        path: /spec/subscription/channel
        value: stable-2.6-cluster-scoped
      - op: add
        path: /spec/versions/-
        value: "aap-operator.v2.6.0-0.1772556740"