---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- alertmanager
- anchore-engine
- apiserver
- applications
- dynatrace-operator
- infra-machineset
- ingress
- namespace-labeling
- openshift-image-registry
- servicemesh
- splunk-connect

patchesStrategicMerge:
- apiserver/cluster-apiserver.yaml
- etcd-backup/etcd-backup-persistentvolume.yaml
- image-registries/regsec.yaml
- ingress/ingresscontroller-default.yaml
- machineconfigs/99-master-kubelet-loglevel.yaml
- self-provisioner/self-provisioner-clusterrolebinding.yaml

patchesJson6902:
- target:
    group: config.openshift.io
    version: v1
    kind: OAuth
    name: cluster
  path: ldap-auth/ldap-oauth.yaml

