apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fluentd-splunk
  namespace: fluentd-splunk
  labels:
    app: fluentd-splunk
spec:
  podManagementPolicy: Parallel
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/infra
      operator: Exists
  replicas: 2
  selector:
    matchLabels:
      app: fluentd-splunk
  template:
    metadata:
      labels:
        app: fluentd-splunk
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - fluentd-splunk
              namespaces:
              - fluentd-splunk
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - name: fluentd-splunk
#        command: ["scl", "enable", "rh-ruby25", "--", "fluentd"]
        command: ["fluentd"]
        image: registry.redhat.io/openshift4/ose-logging-fluentd
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        livenessProbe:
          tcpSocket:
            port: 24224
          periodSeconds: 5
          timeoutSeconds: 3
          initialDelaySeconds: 10
        readinessProbe:
          tcpSocket:
            port: 24224
          periodSeconds: 3
          timeoutSeconds: 2
          initialDelaySeconds: 2
        ports:
        - containerPort: 24224
          name: forwarder-tcp
          protocol: TCP
        - containerPort: 24224
          name: forwarder-udp
          protocol: UDP
        volumeMounts:
        - mountPath: /etc/fluent/
          name: fluentd-splunk
          readOnly: true
        - mountPath: "/var/log/fluentd"
          name: buffer
      volumes:
      - name: fluentd-splunk
        secret:
          defaultMode: 420
          items:
          - key: fluent.conf
            path: fluent.conf
          - key: fluent.crt
            path: fluent.crt
          - key: fluent.key
            path: fluent.key
          - key: splunk-ca.crt
            path: splunk-ca.crt
          secretName: fluentd-splunk
  volumeClaimTemplates:
  - metadata:
      name: buffer
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 10Gi
  updateStrategy:
    type: RollingUpdate

