---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./zzvirtualosvlabadmin-role-binding.yaml
  - ./zzvirtualosvlabautomation-roles-and-rolebinding.yaml
  - ./zzvirtualosvlabreader-group-rolebinding.yaml