alertmanagerMain:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  tolerations:
    - effect: NoSchedule 
      key: node-role.kubernetes.io/infra 
      operator: Exists
  volumeClaimTemplate:
    spec:
      storageClassName: thin
      resources:
        requests:
          storage: 20Gi
prometheusK8s:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  tolerations:
    - effect: NoSchedule 
      key: node-role.kubernetes.io/infra 
      operator: Exists
  volumeClaimTemplate:
    spec:
      storageClassName: thin
      resources:
        requests:
          storage: 80Gi
prometheusOperator:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  tolerations:
    - effect: NoSchedule 
      key: node-role.kubernetes.io/infra 
      operator: Exists 
grafana:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  tolerations:
    - effect: NoSchedule 
      key: node-role.kubernetes.io/infra 
      operator: Exists 
k8sPrometheusAdapter:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  tolerations:
    - effect: NoSchedule 
      key: node-role.kubernetes.io/infra 
      operator: Exists 
kubeStateMetrics:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  tolerations:
    - effect: NoSchedule 
      key: node-role.kubernetes.io/infra 
      operator: Exists 
telemeterClient:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  tolerations:
    - effect: NoSchedule 
      key: node-role.kubernetes.io/infra 
      operator: Exists 
openshiftStateMetrics:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  tolerations:
    - effect: NoSchedule 
      key: node-role.kubernetes.io/infra 
      operator: Exists 
thanosQuerier:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  tolerations:
    - effect: NoSchedule 
      key: node-role.kubernetes.io/infra 
      operator: Exists 
