apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Jaeger.v1.jaegertracing.io
  name: openshift-distributed-tracing-drk8s
  namespace: openshift-distributed-tracing
spec: {}