---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/local-storage-operator/

patches:
  - target:
      kind: OperatorPolicy
      name: local-storage-operator-policy
    patch: |
      - op: replace
        path: /spec/subscription/channel
        value: stable
      - op: add
        path: /spec/versions/-
        value: "local-storage-operator.v4.20.0-202602032049"
