apiVersion: config.openshift.io/v1
kind: Image
metadata:
  name: cluster
spec:
  additionalTrustedCA:
    name: registry-cas
  registrySources:
    allowedRegistries:
    - bsc-docker-all.artifactory.bsc.bscal.com
    - bsc-docker-ci.artifactory.bsc.bscal.com
    - image-registry.openshift-image-registry.svc:5000
    - quay.io/openshift-release-dev
    - registry.access.redhat.com
    - registry.connect.redhat.com
    - registry.redhat.io

