---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/cert-manager-operator/

patches:
  - target:
      kind: OperatorPolicy
      name: cert-manager-operator-policy
    patch: |
      - op: replace
        path: /spec/subscription/channel
        value: stable-v1
      - op: add
        path: /spec/versions/-
        value: "cert-manager-operator.v1.18.1"