apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-kubelet-loglevel
spec:
  config:
    ignition:
      config: {}
      security:
        tls: {}
      timeouts: {}
      version: 2.2.0
    systemd:
      units:
      - dropins:
        - contents: |
            [Service]
            Environment="KUBELET_LOG_LEVEL=1"
          name: 10-kubelet-loglevel.conf
        name: kubelet.service
