apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: argocd-agent-spoke-secrets
placementBindingDefaults:
  name: argocd-agent-spoke-secrets
policyDefaults:
  namespace: open-cluster-management-global-set
  remediationAction: enforce
  complianceType: "mustonlyhave"
policies:
  - name: argocd-agent-spoke-secrets
    description: Argo CD Agent
    hubTemplateOptions:
      serviceAccountName: argocd-agent-policy
    manifests:
      - path: manifests/
    placement:
      placementName: argocd-agent-spoke-secrets
