apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c35,c15
    openshift.io/sa.scc.supplemental-groups: 1001220000/10000
    openshift.io/sa.scc.uid-range: 1001220000/10000
  labels:
    kubernetes.io/metadata.name: dynatrace
  name: dynatrace
spec:
  finalizers:
  - kubernetes