applications: 
  
  web-terminal-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: web-terminal-operator
    source:
      path: clusters/osv1/overlays/web-terminal-operator
  
  external-secrets-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: external-secrets-operator
    source:
      path: clusters/osv1/overlays/external-secrets-operator
  
  external-secrets-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: external-secrets-operator
    source:
      path: clusters/osv1/overlays/external-secrets-configuration
  
  cert-manager-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: cert-manager
    source:
      path: clusters/osv1/overlays/cert-manager-operator
    
  compliance-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: openshift-compliance
    source:
      path: clusters/osv1/overlays/compliance-operator
  
  dell-csm-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    source:
      path: clusters/osv1/overlays/dell-csm-operator
  
  descheduler-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: openshift-kube-descheduler-operator 
    source:
      path: clusters/osv1/overlays/descheduler-operator
                          
  nmstate-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: openshift-nmstate
    source:
      path: clusters/osv1/overlays/nmstate-operator

  node-feature-discovery-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: openshift-nfd
    source:
      path: clusters/osv1/overlays/node-feature-discovery-operator
  
  node-fence-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: openshift-workload-availability
    source:
      path: clusters/osv1/overlays/node-fence-operator

  node-fence-config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: openshift-workload-availability
    source:
      path: clusters/osv1/overlays/node-fence-config
  
  node-health-check-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: openshift-workload-availability
    source:
      path: clusters/osv1/overlays/node-health-check-operator

  node-maintenance-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: openshift-workload-availability
    source:
      path: clusters/osv1/overlays/node-maintenance-operator
  
  osv-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: openshift-cnv
    source:
      path: clusters/osv1/overlays/osv-operator
  
  redhat-otel-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '10'
    destination:
      namespace: openshift-opentelemetry-operator
    source:
      path: clusters/osv1/overlays/redhat-otel-operator
     
  nncp-storage-bond1-vlan-interface:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: clusters/osv1/overlays/nncp-storage-bond1-vlan-interface

  node-labels:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: clusters/osv1/overlays/node-labels
    syncOptions:
      - ServerSideApply=true
