apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: dal-prod-vlan223
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  desiredState:
    interfaces:
      - description: vlan 223  using bond0
        ipv4:
          enabled: false
        name: bond0.223
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 223
      - bridge:
          allow-extra-patch-ports: true
          options:
            stp:
              enabled: false
          port:
            - name: bond0.223
        description: Bridge on VLAN223 using bond0
        ipv4:
          enabled: false
        name: br-223
        state: up
        type: ovs-bridge
    ovn:
      bridge-mappings:
        - bridge: br-223
          localnet: dal-nad-dmz-223
          state: present