---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/vault-secrets-operator/

patches:
  - target:
      kind: OperatorPolicy
      name: vault-secrets-policy
    patch: |
      - op: replace
        path: /spec/subscription/channel
        value: 
      - op: add
        path: /spec/versions/-
        value: ""