apiVersion: v1
kind: Namespace
metadata:
  name: demo-import-cluster
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: demo-import-cluster
  labels:
    name: demo-import-cluster
    cloud: auto-detect
    vendor: auto-detect
    environment: prod
    cluster.open-cluster-management.io/clusterset: non-local
  annotations: {}
spec:
  hubAcceptsClient: true
---
apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: demo-import-cluster
stringData:
  autoImportRetry: "2"
  token: *REDACTED*
  server: $CLUSTER_API_ADDRESS
type: Opaque
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: demo-import-cluster
  namespace: demo-import-cluster
spec:
  clusterName: demo-import-cluster
  clusterNamespace: demo-import-cluster
  clusterLabels:
    name: demo-import-cluster
    cloud: auto-detect
    vendor: auto-detect
    environment: prod
    cluster.open-cluster-management.io/clusterset: non-local
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
