---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/mtv-operator/

patches:
  - target:
      kind: OperatorPolicy
      name: mtv-operator-policy
    patch: |
      - op: replace
        path: /spec/subscription/channel
        value: release-v2.10
      - op: add
        path: /spec/versions/-
        value: "mtv-operator.v2.10.6"
