apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-agent-principal-tls
  namespace: argocd
spec:
  dnsNames:
    - argocd-agent-principal-argocd.apps.hub1.ocp.jobu.net
  issuerRef:
    name: argocd-agent-ca
    kind: Issuer
  commonName: principal
  secretName: argocd-agent-principal-tls
  subject:
    organizationalUnits:
      - hub1.ocp.jobu.net