apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anchore-enterprise
  namespace: openshift-gitops
spec:
  destination:
    namespace: anchore-enterprise
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      valueFiles:
        - anchore_values.yaml
    path: gitops-cluster-config/npek8s/anchore-engine/helm
    repoURL: 'https://bitbucket.blueshieldca.com/scm/caa/openshift_playbooks.git'
    targetRevision: HEAD
