---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ldap-group-syncer
  namespace: openshift-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ldap-group-syncer
rules:
- apiGroups:
  - ""
  resources:
  - groups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ldap-group-syncer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ldap-group-syncer
subjects:
- kind: ServiceAccount
  name: ldap-group-syncer
  namespace: openshift-config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ldap-group-sync
  namespace: openshift-config
spec:
  schedule: "0 */4 * * *"  # Run every 4 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ldap-group-sync
            image: registry.redhat.io/openshift4/ose-cli:latest
            command:
            - /bin/bash
            - -c
            - |
              oc adm groups sync --whitelist=/etc/config/whitelist.txt --sync-config=/etc/config/ldap-sync.yaml --confirm
            volumeMounts:
            - name: ldap-sync-volume
              mountPath: /etc/config
            - name: ldap-secret-volume
              mountPath: /etc/ldap-secret
          volumes:
          - name: ldap-sync-volume
            configMap:
              name: ldap-sync-config
          - name: ldap-secret-volume
            secret:
              secretName: ldap-password
          restartPolicy: Never
          serviceAccountName: ldap-group-syncer  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-sync-config
  namespace: openshift-config
data:
  ldap-sync.yaml: |
    kind: LDAPSyncConfig
    apiVersion: v1
    url: 
    insecure: false
    bindDN: ''
    bindPassword:
      file: "/etc/ldap-secret/bindPassword"
    groupUIDNameMapping:
      "CN=": Virtual_Infra_Eng_Adm
      "CN=": VirtualOSVLabAdmin
      "CN=": VirtualOSVLabAutomation
      "CN=": VirtualOSVLabReader
    activeDirectory:
      usersQuery:
        baseDN: ""
        scope: sub
        derefAliases: never
        filter: (objectclass=person)
        pageSize: 0
      userNameAttributes: [ sAMAccountName ]
      groupMembershipAttributes: [ memberOf ]
  whitelist.txt: |
    CN=MATCH
    CN=LISTED
    CN=CNS
    CN=ABOVE
    