apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ldap-password
  namespace: openshift-config
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default	
        decodingStrategy: None
        key: ldap-password
        metadataPolicy: None
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets-vault-ss
  target:
    creationPolicy: Owner
    name: ldap-password