apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: opentlc-ldap
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        email: []
        id:
        - dn
        name:
        - cn
        preferredUsername:
        - sAMAccountName
      bindDN: ""
      bindPassword:
        name: ldap-password
      # ca:
      #   name: opentlc-ca-config-map
      insecure: false
      url: ""
