---
apiVersion: v1
kind: Namespace
metadata:
  name: etcd-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: default
  namespace: etcd-backup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-backup-pvc
  namespace: etcd-backup
spec:
  volumeName: etcd-backup-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: etcd-backup
  namespace: etcd-backup
spec:
  concurrencyPolicy: Forbid
  schedule: "0 1,13 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etcd-backup
            image: registry.redhat.io/openshift4/ose-tools-rhel8
            command: ["/bin/bash", "-c", "chroot /host /usr/local/bin/cluster-backup.sh /home/backups && find /host/home/backups -type f -mtime +30 -delete"]
            securityContext:
              privileged: true
              runAsUser: 0
            volumeMounts:
            - mountPath: /host
              name: host
              readOnly: true
            - mountPath: /host/home/backups
              name: etcd-backup-pvc
          restartPolicy: Never
          hostNetwork: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
            operator: Exists
          volumes:
          - name: host
            hostPath:
              path: /
              type: Directory
          - name: etcd-backup-pvc
            persistentVolumeClaim:
              claimName: etcd-backup-pvc

