apiVersion: v1
kind: Secret
metadata:
  name: repo-ssh
  namespace: argocd-agent
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  sshPrivateKey: '{{hub (fromSecret "argocd" "repo-ssh"  "sshPrivateKey") hub}}'
  url: '{{hub (fromSecret "argocd" "repo-ssh"  "url") hub}}'
  type: '{{hub (fromSecret "argocd" "repo-ssh"  "type") hub}}'
