---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-cluster-configs
rules:
- apiGroups:
  - imageregistry.operator.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - template.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - '*'
  resources:
  - limitranges
  - resourcequotas
  - secrets
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - argoproj.io
  resources:
  - argocds
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - services
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - '*'
- apiGroups:
  - dynatrace.com
  resources:
  - dynakubes
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - '*'

