---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  disableAdmin: false
  applicationSet:
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
  controller:
    processors: {}
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    sharding: {}
  dex:
    openShiftOAuth: true
    groups:
    - cluster_admin
    - rbac-openshift-admin
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  grafana:
    enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
    route:
      enabled: false
  ha:
    enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  initialSSHKnownHosts: {}
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  rbac:
    policy: | 
      g, cluster_admin, role:admin
      g, rbac-openshift-admin, role:admin
    scopes: '[groups]'
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  repo:
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    route:
      enabled: true
    service:
      type: ""
  tls:
    ca: {}
    initialCerts:
      bitbucket.blueshieldca.com: |
        -----BEGIN CERTIFICATE-----
        MIIH6jCCBdKgAwIBAgITTAAAAAY71PEmhYhVrgAAAAAABjANBgkqhkiG9w0BAQsF
        ADAVMRMwEQYDVQQDEwpCU0NST09UQ0EyMB4XDTE5MDkwMzE5MTA1MVoXDTI0MDkw
        MzE5MjA1MVowVzETMBEGCgmSJomT8ixkARkWA2NvbTEVMBMGCgmSJomT8ixkARkW
        BWJzY2FsMRMwEQYKCZImiZPyLGQBGRYDYnNjMRQwEgYDVQQDEwtCU0NJU1NVRUNB
        MjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAI2wZxM8kIHM3DUF0r/l
        WnE17fZwvNhreZ8OgzKnpzy0DMp96MWJv9C+eeyM/3rXQR4MUSYaloApTSAkf9MP
        AG7xJD82oN6amIVzT5FiTb3BAw3CBQMK3d+bX8kCO1aQmhlisGHaZSO5qoVQDvWL
        mU/dehRfyFJ0sAQQXjO6bnlTqBnTBGxAsld2dJjUNds8bnB8Jn/PBbap+iXTOGrw
        QiXISabCRAXMPwZzrRAVYdr4dy69+8iS8VHsisZK3Y4RChG2QuyVJyIBKXoaot/V
        0n/YuFtL+OaWogLd6EJ6qGj0soZkBxAjOj5Who9JgGpfV52EN76q979u8RjMub6+
        rsypH+1QFZ90NBCKZe35fqaf48ue9mv5G24xK0qUquYAmlDsZq83xlsYIM/SqEQP
        wa9d6wDEumu53XpiSMgpWjgBQVJZVj1uXJV34w8MLZggTdqDQB7zxJp2zbxNzvv5
        w+hn54/eh9RJ9Tl7M8ROPI+LSlT66LocNV8IpA7WeLAeoZ11y2CW6rI0SnLcCMJo
        uKCdPAKCSClTwC145MnM5X3qgs20M3Fe9R4z9Q9KYjpUGO14OR8UDSVKVC6fWMnJ
        05P6gBQTQGUKElbSmjpzzYUJ3zpaTJxKQBtAg7cPX4PuLvll0nbpkdYYeT+9tSPM
        AsQ2wSRUxiZ/J9sRL/ok9TONAgMBAAGjggLvMIIC6zAQBgkrBgEEAYI3FQEEAwIB
        BDAjBgkrBgEEAYI3FQIEFgQUQUpfYzLsQOWZQdpzSSgre13MbmEwHQYDVR0OBBYE
        FKPRwRLfSt8aRknd/MA7nJ47O8rIMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBB
        MAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8GA1UdIwQYMBaAFHql+K/J
        D/OHWJm6VYQndp8/3qQuMIIBAwYDVR0fBIH7MIH4MIH1oIHyoIHvhoG3bGRhcDov
        Ly9DTj1CU0NST09UQ0EyLENOPXdpbmY0MThwLENOPUNEUCxDTj1QdWJsaWMlMjBL
        ZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPWJz
        YyxEQz1ic2NhbCxEQz1jb20/Y2VydGlmaWNhdGVSZXZvY2F0aW9uTGlzdD9iYXNl
        P29iamVjdENsYXNzPWNSTERpc3RyaWJ1dGlvblBvaW50hjNodHRwOi8vcGtpMi5i
        c2MuYnNjYWwuY29tL3JlcG9zaXRvcnkvQlNDUk9PVENBMi5jcmwwggEwBggrBgEF
        BQcBAQSCASIwggEeMIGuBggrBgEFBQcwAoaBoWxkYXA6Ly8vQ049QlNDUk9PVENB
        MixDTj1BSUEsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMs
        Q049Q29uZmlndXJhdGlvbixEQz1ic2MsREM9YnNjYWwsREM9Y29tP2NBQ2VydGlm
        aWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MD8G
        CCsGAQUFBzAChjNodHRwOi8vcGtpMi5ic2MuYnNjYWwuY29tL3JlcG9zaXRvcnkv
        QlNDUk9PVENBMi5jcnQwKgYIKwYBBQUHMAGGHmh0dHA6Ly9wa2kyLmJzYy5ic2Nh
        bC5jb20vb2NzcDANBgkqhkiG9w0BAQsFAAOCAgEAXK+ygVGf9Nev0pfTiWEvXcyz
        lSW+hQPhaOJnH21aJoJzkQXPc5Aud+YGwSgKV0qIOwhx1x9I3sNz9/z276zi/AaO
        EgrQOZrJxQRToo1bZuPW+0WMfqv2yMhkIUqJaNHwD+iNvyQz3PvC6HFrPNqLJsmq
        IfJrq5eVemImXcKBfGuGYuaIges63hHl9HyKOSKTbk2qjFqTyW9DpEJNf7ABTYq5
        Fy4ahIDhj6e1WDvEQ0pTuivVn5A/MHhFiWfFWmeXCGosQlB4OzeV6nk7fzkP7DDe
        rP8doxonONT9vO4bFHrP8Ktv6O6h6lfBW8nBmW3x0aFQP+w9IuFfuF4B1iC2MSWn
        g4dXJRTD549FklltSmKWMbS0owyqtQwoqBbD9DBGQRcxfRzmjv6cQTnVmHr2kesT
        HQuBtV/3Y40WGYz+N+ThafbuZZNMxqxsCJ4L3ydGci1h8hpuDj3a6Ug++L00MckK
        by3FI3NjmsPmRly7CRNBZNayPt6RPcttnQY4HgEjXedhs+WqDDd85jYd/nSwq7HR
        b1Jvrf9nIJq/Oj7ToGSuVOqDz7dG5LFYD18u5RdHwHvzCAUtoYTM8wSYgdTsyl7o
        UMk+5luwm0qLw+8PwAwuqYI1LGgxMCtS8/8dD6RlYUXADaWw6x/EHTDqJsDGdbsa
        GbDmZYQp7XGjugNQQuI=
        -----END CERTIFICATE-----
  initialRepositories: |
    - url: https://bitbucket.blueshieldca.com/scm/caa/openshift_playbooks.git
      usernameSecret:
        name: bitbucket
        key: username
      passwordSecret:
        name: bitbucket
        key: accesstoken

