---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
    - names:
      - api.prodk8s.bsc.bscal.com
      servingCertificate:
        name: apiserver-cert

