---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: digital-applications
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops-cluster-config/npek8s/applications/fad
    repoURL: https://bitbucket.blueshieldca.com/scm/caa/openshift_playbooks.git
    targetRevision: master