---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-agent-resource-proxy-tls
  namespace: argocd
spec:
  secretName: argocd-agent-resource-proxy-tls
  issuerRef:
    name: argocd-agent-ca
    kind: Issuer
  commonName: argocd-agent-principal-resource-proxy
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - argocd-agent-principal-resource-proxy.argocd.svc.cluster.local
    - argocd-agent-principal-resource-proxy.argocd.svc
  usages:
    - server auth
