apiVersion: v2
appVersion: 1.1.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: file://./deps/postgresql
  version: 1.0.1
- alias: anchore-feeds-db
  condition: anchore-feeds-db.enabled,anchoreEnterpriseGlobal.enabled
  name: postgresql
  repository: file://./deps/postgresql
  version: 1.0.1
- alias: anchore-feeds-gem-db
  condition: anchore-feeds-gem-db.enabled,anchoreEnterpriseFeeds.gemDriverEnabled
  name: postgresql
  repository: file://./deps/postgresql
  version: 1.0.1
- alias: anchore-ui-redis
  condition: anchore-ui-redis.enabled,anchoreEnterpriseGlobal.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: "10"
description: Anchore container analysis and policy evaluation engine service
home: https://anchore.com
icon: https://anchore.com/wp-content/uploads/2016/08/anchore.png
keywords:
- analysis
- docker
- anchore
- anchore-engine
- image
- security
- vulnerability
- scanner
maintainers:
- email: zach@anchore.com
  name: zhill
- email: bradyt@anchore.com
  name: btodhunter
name: anchore-engine
sources:
- https://github.com/anchore/anchore-engine
version: 1.18.1
