---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: istio-releasetest-digital
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 100m
      memory: 256Mi

