---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: project-resources
  namespace: istio-opstest-digital
spec:
  hard:
    limits.ephemeral-storage: 8Gi
    requests.cpu: 8
    requests.ephemeral-storage: 4Gi
    requests.memory: 32Gi
    requests.storage: 200Gi
    persistentvolumeclaims: 5

