apiVersion: v1
kind: PersistentVolume
metadata:
  name: opstest2-digital-pv
spec:
  capacity:
    storage: 200G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    server: lasbscnpe.bsc.bscal.com
    path: /npe_docs/aipn06
