apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fence-agents-credentials-shared
  namespace: openshift-workload-availability
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default	
        decodingStrategy: None
        key: fence-agent/redfish
        metadataPolicy: None
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets-vault-ss
  target:
    creationPolicy: Owner
    name: fence-agents-credentials-shared