apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: acs-policy
  namespace: open-cluster-management-global-set
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: acs-operator-policy
        spec:
          remediationAction: enforce
          complianceType: musthave
          subscription:
            name: rhacs-operator
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          versions:
            - "4.6.0"
            - "4.6.1"
            - "4.6.2"
          upgradeApproval: Automatic
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: acs-placement
  namespace: open-cluster-management-global-set
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - {key: argocd-agent, operator: Exists}
            - {key: local-cluster, operator: DoesNotExist}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: acs-placement-binding
  namespace: open-cluster-management-global-set
placementRef:
  name: acs-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: acs-policy
    apiGroup: policy.open-cluster-management.io
    kind: Policy
