---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: local-storage-policy
  namespace: open-cluster-management-global-set
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: local-storage-operator-policy
        spec:
          remediationAction: enforce
          complianceType: musthave
          subscription:
            name: local-storage-operator
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          versions:
            - "4.16.0"
            - "4.16.1"
            - "4.17.0"
          upgradeApproval: Automatic
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: local-storage-placement
  namespace: open-cluster-management-global-set
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - {key: argocd-agent, operator: Exists}
            - {key: local-cluster, operator: Exists}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: local-storage-placement-binding
  namespace: open-cluster-management-global-set
placementRef:
  name: local-storage-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: local-storage-policy
    apiGroup: policy.open-cluster-management.io
    kind: Policy
---
