---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: mtv-policy
  namespace: open-cluster-management-global-set
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: mtv-operator-policy
        spec:
          remediationAction: enforce
          complianceType: musthave
          subscription:
            name: mtv-operator
            channel: release-v2.6
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          versions:
            - "2.6.0"
            - "2.6.1"
            - "2.6.2"
          upgradeApproval: Automatic
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: mtv-placement
  namespace: open-cluster-management-global-set
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - {key: argocd-agent, operator: Exists}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: mtv-placement-binding
  namespace: open-cluster-management-global-set
placementRef:
  name: mtv-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: mtv-policy
    apiGroup: policy.open-cluster-management.io
    kind: Policy
---
