---
  
- name: create appdynamics namespace
  k8s:
    definition: "{{ lookup('file', 'appdynamics-namespace.yaml') }}"

- name: install and configure appdynamics cluster agent secret
  k8s:
    definition: "{{ lookup('template', 'cluster-agent-secret.yaml.j2') }}"

- name: install and configure appdynamics
  k8s:
    definition: "{{ lookup('file', '{{ item }}') }}"
  loop:
    - components.yaml
    - cluster-agent-operator.yaml

- name: install and configure appdynamics cluster agent
  k8s:
    definition: "{{ lookup('template', 'cluster-agent.yaml.j2') }}"

- name: add security context constraint for infraviz
  k8s:
    definition: "{{ lookup('file', 'infraviz-security-context-constraint-openshift.yaml') }}"

- name: install and configure infraviz
  k8s:
    definition: "{{ lookup('template', 'infraviz.yaml.j2') }}"
