---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: node-fence-operator-policy
  namespace: open-cluster-management-policies
spec:
  remediationAction: enforce
  complianceType: musthave
  severity: critical
  # operatorGroup:
  #   name: openshift-workload-availability
  #   namespace: openshift-workload-availability
  #   targetNamespaces:
  #     - openshift-workload-availability
  subscription:
    name: fence-agents-remediation
    namespace: openshift-workload-availability
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: fence-agents-remediation.v0.6.1
  versions: []
  upgradeApproval: Automatic
