---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cicd-limitrange.yaml
- cicd-networkpolicy.yaml
- cicd-resourcequota.yaml
- prod-digital-limitrange.yaml
- prod-digital-namespace.yaml
- prod-digital-networkpolicy.yaml
- prod-digital-pv.yaml
- prod-digital-rbac.yaml
- prod-digital-resourcequota.yaml
- istio-prod-digital-limitrange.yaml
- istio-prod-digital-rbac.yaml
- istio-prod-digital-namespace.yaml
- istio-prod-digital-resourcequota.yaml
