---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-namespace-labeler
rules:
- apiGroups:
  - ''
  resources:
  - namespaces
  - configmaps
  verbs:
  - 'list'
  - 'get'
  - 'patch'
  - 'create'
- apiGroups:
  - 'apps'
  resources:
  - deployments
  verbs:
  - 'get'
  - 'patch'
