---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpd-unlabeled-ns
  namespace: namespace-labeler
  labels:
    app: httpd-unlabeled-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-unlabeled-ns
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd-unlabeled-ns
    spec:
      volumes:
        - name: site-data
          configMap:
            name: system-created-unlabeled-ns
            defaultMode: 420
      containers:
        - name: httpd-unlabeled-ns
          image: registry.redhat.io/rhel8/httpd-24
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: site-data
              mountPath: /var/www/html
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
