kind: ConfigMap
apiVersion: v1
metadata:
  name: job-sh
  namespace: namespace-labeler
data:
  job.sh: >-
    #!/bin/bash
      
    for file in /etc/ns-files/*; do
      for i in $(cat /etc/ns-files/${file##*/}); do 
        oc label namespace $i owner=${file##*/} --overwrite; 
      done
    done 
    
    oc get namespace --selector="owner" -o template --template '{{range.items}}{{.metadata.name}}{{"\n"}}{{end}}' > ~/tmp/ns-owned;   
    oc get namespace -o template --template '{{range.items}}{{.metadata.name}}{{"\n"}}{{end}}' > ~/tmp/ns-all; 

    grep -Fxvf ~/tmp/ns-owned ~/tmp/ns-all > ~/tmp/unlabeled;
    echo "unlabeled_count $(wc -l < ~/tmp/unlabeled)" > ~/tmp/unlabeled.json;
    if [ -s ~/tmp/unlabeled ]; then
      echo 'The following namespaces are unlabeled:';  
      cat ~/tmp/unlabeled;
    fi
    
    cd ~/tmp;
    oc create configmap system-created-unlabeled-ns --from-file=unlabeled.json --dry-run=client -o yaml > ~/tmp/configmap-gen.yaml; 
    oc apply -f ~/tmp/configmap-gen.yaml;
    oc patch deployment/httpd-unlabeled-ns --patch "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"last-restart\":\"`date +'%s'`\"}}}}}";
