---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- job-sh-cm.yaml
- namespace-labeler-ns.yaml
- service.yaml
- serviceaccount.yaml
- servicemonitor.yaml
