---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dev1-digital-limitrange.yaml
- dev1-digital-namespace.yaml
- dev1-digital-pv.yaml
- dev1-digital-rbac.yaml
- dev1-digital-resourcequota.yaml
- istio-dev1-digital-limitrange.yaml
- istio-dev1-digital-namespace.yaml
- istio-dev1-digital-rbac.yaml
- istio-dev1-digital-resourcequota.yaml
- dev2-digital-limitrange.yaml
- dev2-digital-namespace.yaml
- dev2-digital-pv.yaml
- dev2-digital-rbac.yaml
- dev2-digital-resourcequota.yaml
- istio-dev2-digital-limitrange.yaml
- istio-dev2-digital-namespace.yaml
- istio-dev2-digital-rbac.yaml
- istio-dev2-digital-resourcequota.yaml
- monitor-digital-limitrange.yaml
- monitor-digital-namespace.yaml
- monitor-digital-rbac.yaml
- monitor-digital-resourcequota.yaml
- qa1-digital-limitrange.yaml
- qa1-digital-namespace.yaml
- qa1-digital-pv.yaml
- qa1-digital-rbac.yaml
- qa1-digital-resourcequota.yaml
- istio-qa1-digital-limitrange.yaml
- istio-qa1-digital-namespace.yaml
- istio-qa1-digital-rbac.yaml
- istio-qa1-digital-resourcequota.yaml
- qa2-digital-limitrange.yaml
- qa2-digital-namespace.yaml
- qa2-digital-pv.yaml
- qa2-digital-rbac.yaml
- qa2-digital-resourcequota.yaml
- istio-qa2-digital-limitrange.yaml
- istio-qa2-digital-namespace.yaml
- istio-qa2-digital-rbac.yaml
- istio-qa2-digital-resourcequota.yaml
