---
object-templates-raw: |
  {{- range $mc := (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" "" "argocd-agent").items }}
    {{- $mc_name := $mc.metadata.name }}
    {{- $agent_name := (index $mc.metadata.labels "argocd-agent")}}

  - complianceType: mustonlyhave
    objectDefinition:
      kind: Namespace
      apiVersion: v1
      metadata:
        name: argocd-agent-{{ $agent_name }}

  - complianceType: mustonlyhave
    objectDefinition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: argocd-agent-{{ $agent_name }}
        namespace: argocd
      spec:
        secretName: argocd-agent-{{ $agent_name }}
        issuerRef:
          name: argocd-agent-ca
          kind: Issuer
        commonName: argocd-agent-{{ $agent_name }}
        subject:
          organizationalUnits:
            - shanehomelab.com
        usages:
          - client auth
        dnsNames:
        - argocd-agent-{{ $agent_name }}.ocp.jobu.net

  - complianceType: mustonlyhave
    objectDefinition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: argocd-principal-{{ $agent_name }}
        namespace: argocd
      spec:
        secretName: argocd-principal-{{ $agent_name }}
        issuerRef:
          name: argocd-agent-ca
          kind: Issuer
        commonName: argocd-agent-{{ $agent_name }}
        subject:
          organizationalUnits:
            - shanehomelab.com
        dnsNames:
        - argocd-agent-{{ $agent_name }}.ocp.jobu.net

  {{- end }}
