---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/aap-operator/
  
patches:
  - target:
      kind: OperatorPolicy
      name: compliance-policy
    patch: |
      - op: replace
        path: /spec/subscription/channel
        value: stable  
      - op: add
        path: /spec/versions/-
        value: "1.7.2"
