---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/aap-operator/
  
patches:
  - target:
      kind: Policy
      name: aap-policy
    patch: |
      - op: replace
        path: /spec/subscription/channel
        value: stable-2.5  
      - op: replace
        path: /spec/policy-templates/0/objectDefinition/spec/versions/0
        value: "2.5.2"
