apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: $BUCKET_NAME
      endpoint: $BUCKET_ENDPOINT #(s3.us-east-2.amazonaws.com for AWS)
      insecure: true
      access_key: $AWS_ACCESS_KEY
      secret_key: $AWS_SECRET_KEY
