apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: $BUCKET_NAME
      endpoint: s3.openshift-storage.svc:443
      insecure: true
      access_key: *REDACTED*
      secret_key: *REDACTED*
