apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: nb.1668031086996.cluster-64r66.64r66.sandbox2712.opentlc.com
      endpoint: s3.us-east-2.amazonaws.com
      insecure: true
      access_key: *REDACTED*
      secret_key: *REDACTED*