---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../components/acm-operator/

patches:
  - target:
      kind: OperatorPolicy
      name: acm-operator-policy
    patch: |
      - op: replace
        path: /spec/subscription/channel
        value: release-2.15
      - op: add
        path: /spec/versions/-
        value: "advanced-cluster-management.v2.15.1"