apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rhacm-aws-creds
  namespace: aws-creds
  labels:
    cluster.open-cluster-management.io/credentials: ""
    cluster.open-cluster-management.io/type: aws
  annotations:
    credential-hash: JfkYxMT4wudhCRgbsdKilPYwNm9VTkF+jnhiocMiwzg=
stringData:
  aws_access_key_id: "********************"
  aws_secret_access_key: "********************"
  baseDomain: foo.com
  pullSecret: "********************"
  ssh-privatekey: "********************"
  ssh-publickey: "********************"
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""
  additionalTrustBundle: ""