apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rhacm-aws-creds
  namespace: aws-creds
  labels:
    cluster.open-cluster-management.io/credentials: ""
    cluster.open-cluster-management.io/type: aws
stringData:
  aws_access_key_id: REDACTED
  aws_secret_access_key: REDACTED
  baseDomain: foo.com
  pullSecret: >
    REDACTED
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    
    -----END OPENSSH PRIVATE KEY-----
  ssh-publickey: >
    REDACTED
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""
  additionalTrustBundle: ""
