---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- apiserver
- argo-cicd
- chrony
- compliance-operator
- etcd-backup
- image-registries
- ingress
- kubeletconfig
- ldap-auth
- ldap-groupsync
- machineconfig
- monitoring-config
- namespace-labeling
- project-request
- sealed-secrets
- self-provisioner
#- splunk-connect
- trusted-ca

