apiVersion: fence-agents-remediation.medik8s.io/v1alpha1
kind: FenceAgentsRemediationTemplate
metadata:
  name: fenceagentsremediationtemplate-default
  namespace: openshift-workload-availability
spec:
  template:
    spec:
      agent: fence_redfish
      nodeparameters:
        '--ip':       
           0sv-node-ctl001.ocp.jobu.net: 10.0.40.
           0sv-node-ctl002.ocp.jobu.net: 10.0.40.
           0sv-node-ctl003.ocp.jobu.net: 10.0.40.
           0sv-node-wrk001.ocp.jobu.net: 10.0.40.
           0sv-node-wrk002.ocp.jobu.net: 10.0.40.
           0sv-node-wrk003.ocp.jobu.net: 10.0.40.
           0sv-node-wrk004.ocp.jobu.net: 10.0.40.
      remediationStrategy: ResourceDeletion
      retrycount: 5
      retryinterval: 5s
      sharedSecretName: fence-agents-credentials-shared
      sharedparameters:
        '--action': reboot
        '--ipport': '443'
        '--ssl-insecure': ''
        '--systems-uri': /redfish/v1/Systems/System.Embedded.1
      timeout: 1m0s