apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitops-argocd-role
  namespace: sealed-secrets
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
