---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- controller.yaml
- gitops-argocd-role.yaml
- gitops-argocd-rolebinding.yaml
- sealed-secrets-clusterrole.yaml
- sealed-secrets-clusterrolebinding.yaml
