---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - managedcluster.yaml
  #- vault-auth-osv1.yaml
  #- vaultstaticsecret.yaml
  - klusterletaddonconfig.yaml
  #- managedclustersetbinding.yaml