---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: auto-import-secret
  namespace: osv1
spec:
  type: kv-v2
  mount: kv-v2/openshift-platform-services
  path: osv1/kube-config
  vaultAuthRef: vaultauth
  destination:
    create: true
    overwrite: false
    name: auto-import-secret
  refreshAfter: "1h"
  hmacSecretData: true
  # fields:
  #   - kubeconfig
