apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./storage-cluster.yaml
  - ./console-plugin-enable.yaml
  #- ./ocs-initialization.yaml
  #- ./storage-system.yaml
  #- ./console-plugin.yaml

  