apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-cluster-management-observability

resources:
  - ./namespace.yaml
  - ./pull-secret.yaml
  - ./thanos-object-storage-secret.yaml
  - ./multicluster-observability.yaml
#  - ./object-bucket-claim.yaml - Move to ODF setup pre-bootstrap. Manually created bucket from file using oc create -f
#  - ./link.yaml - CR for generating the ACMMO link for older versions of the operator.
#  - ./rbac.yaml - Rolebinding for a ServiceAccount named acmmo that does not exist in the cluster yet.