apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: 
      endpoint: s3.openshift-storage.svc:443
      insecure: false
      access_key: 
      secret_key: 
      http_config:
        ca_file:"/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"