#
# Deploy the logging component to OpenShift.
#
# Additionally the system:openshift:scc:privileged ClusterRoleBinding for
# the fluentd pod ServiceAccount needs to be created manually.
#
---
global:
  splunk:
    hec:
      token: 73806eda-f4ae-4a32-8444-50a86924be67
      host: uinf4000p.bsc.bscal.com
      port: 8088
      indexName: openshift
      insecureSSL: true 
  kubernetes:
    clusterName: prodk8s

splunk-kubernetes-logging:
  enabled: true
  kubernetes:
    # the next actually sets .securityContext.privileged
    # privileged is required, due to SELinux preventing
    # write access for the *.pos files of fluentd.
    securityContext: true
  containers:
    logFormatType: cri
    logFormat: "%Y-%m-%dT%H:%M:%S.%N%:z"
  logs:
    # The `kube-audit` file has another path on OpenShift
    kube-audit:
      from:
        file:
          path: /var/log/kube-apiserver/audit.log
    # Next 2 logfiles are specific to OpenShift
    openshift-audit:
      from:
        file:
          path: /var/log/openshift-apiserver/audit.log
      timestampExtraction:
        format: "%Y-%m-%dT%H:%M:%SZ"
      sourcetype: kube:openshift-apiserver-audit
    oauth-audit:
      from:
        file:
          path: /var/log/oauth-apiserver/audit.log
      timestampExtraction:
        format: "%Y-%m-%dT%H:%M:%SZ"
      sourcetype: kube:oauth-apiserver-audit
  image:
    registry: bsc-docker-all.artifactory.bsc.bscal.com
    name: ice/splunk/fluentd-hec
    tag: 1.2.11
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
    - key: node-role.kubernetes.io/infra
      effect: NoSchedule
      operator: Exists
splunk-kubernetes-metrics:
  enabled: false

splunk-kubernetes-objects:
  enabled: false

